hostname sb051.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:e0 brd ff:ff:ff:ff:ff:ff inet 10.3.81.131/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c9e0/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:e1 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:e2 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:e3 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:b0 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.131/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.131/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f6b0/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:b1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-02-01 06:18:21,208 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.131:33526'
2024-02-01 06:18:35,733 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.131:45699
2024-02-01 06:18:35,734 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.131:45699
2024-02-01 06:18:35,734 - distributed.worker - INFO -           Worker name:           SLURMCluster-114
2024-02-01 06:18:35,734 - distributed.worker - INFO -          dashboard at:          10.3.89.131:32957
2024-02-01 06:18:35,734 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 06:18:35,734 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:18:35,734 - distributed.worker - INFO -               Threads:                          2
2024-02-01 06:18:35,734 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 06:18:35,734 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-n9cu7cuq
2024-02-01 06:18:35,735 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:18:35,787 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 06:18:35,787 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 06:18:35,788 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 06:30:28,128 - distributed.core - INFO - Event loop was unresponsive in Nanny for 64.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:30:28,129 - distributed.core - INFO - Event loop was unresponsive in Worker for 64.10s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:30:31,858 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.73s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:45:51,826 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.04s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:45:56,333 - distributed.core - INFO - Event loop was unresponsive in Worker for 4.51s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 06:52:13,148 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.35s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:01:24,062 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.73s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:28,513 - distributed.core - INFO - Event loop was unresponsive in Worker for 59.33s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:28,513 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 59.33s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 07:15:11,542 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 12 conformers. 
Removed 4 conformers. 
Generated 38 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  12%|██▉                    | 1/8 [00:03<00:21,  3.12s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:04<00:13,  2.18s/it]Optimising conformer:  38%|████████▋              | 3/8 [00:07<00:13,  2.70s/it]Optimising conformer:  50%|███████████▌           | 4/8 [00:11<00:11,  2.91s/it]Optimising conformer:  62%|██████████████▍        | 5/8 [00:14<00:08,  2.91s/it]Optimising conformer:  75%|█████████████████▎     | 6/8 [00:16<00:05,  2.79s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:20<00:02,  2.98s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:22<00:00,  2.76s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:22<00:00,  2.79s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 78.4s.
TIME changed dir: 0.0s
Generated 46 conformers. 
Removed 26 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/9 [00:00<?, ?it/s]Optimising conformer:  11%|██▌                    | 1/9 [00:03<00:24,  3.11s/it]Optimising conformer:  22%|█████                  | 2/9 [00:05<00:17,  2.43s/it]Optimising conformer:  33%|███████▋               | 3/9 [00:13<00:29,  4.96s/it]Optimising conformer:  44%|██████████▏            | 4/9 [00:17<00:22,  4.57s/it]Optimising conformer:  56%|████████████▊          | 5/9 [00:20<00:16,  4.04s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                              | 0/20 [00:00<?, ?it/s][AOptimising conformer:  67%|███████████████▎       | 6/9 [00:23<00:11,  3.77s/it]Optimising conformer:  78%|█████████████████▉     | 7/9 [00:25<00:06,  3.16s/it]
Optimising conformer:   5%|█                     | 1/20 [00:03<01:09,  3.64s/it][AOptimising conformer:  89%|████████████████████▍  | 8/9 [00:28<00:03,  3.19s/it]
Optimising conformer:  10%|██▏                   | 2/20 [00:08<01:14,  4.15s/it][A
Optimising conformer:  15%|███▎                  | 3/20 [00:09<00:52,  3.08s/it][AOptimising conformer: 100%|███████████████████████| 9/9 [00:36<00:00,  4.72s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:36<00:00,  4.07s/it]

Optimising conformer:  20%|████▍                 | 4/20 [00:13<00:53,  3.32s/it][A
Optimising conformer:  25%|█████▌                | 5/20 [00:17<00:51,  3.45s/it][A/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")

Optimising conformer:  30%|██████▌               | 6/20 [00:20<00:48,  3.44s/it][A
Optimising conformer:  35%|███████▋              | 7/20 [00:23<00:43,  3.32s/it][A
Optimising conformer:  40%|████████▊             | 8/20 [00:27<00:41,  3.49s/it][A
Optimising conformer:  45%|█████████▉            | 9/20 [00:32<00:42,  3.86s/it][A2024-02-01 07:17:06,381 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 13)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)

Optimising conformer:  50%|██████████▌          | 10/20 [00:36<00:39,  3.97s/it][A2024-02-01 07:17:08,776 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 13)


Optimising conformer:  55%|███████████▌         | 11/20 [00:38<00:30,  3.44s/it][A
Optimising conformer:  60%|████████████▌        | 12/20 [00:41<00:26,  3.31s/it][A
Optimising conformer:  65%|█████████████▋       | 13/20 [00:45<00:23,  3.30s/it][A
Optimising conformer:  70%|██████████████▋      | 14/20 [00:47<00:18,  3.13s/it][A
Optimising conformer:  75%|███████████████▊     | 15/20 [00:50<00:14,  2.95s/it][A
Optimising conformer:  80%|████████████████▊    | 16/20 [00:52<00:11,  2.85s/it][A
Optimising conformer:  85%|█████████████████▊   | 17/20 [00:56<00:09,  3.02s/it][A
Optimising conformer:  90%|██████████████████▉  | 18/20 [01:00<00:06,  3.29s/it][A
Optimising conformer:  95%|███████████████████▉ | 19/20 [01:03<00:03,  3.15s/it][A
Optimising conformer: 100%|█████████████████████| 20/20 [01:05<00:00,  2.97s/it][AOptimising conformer: 100%|█████████████████████| 20/20 [01:05<00:00,  3.28s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 07:17:58,172 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 9)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 07:17:59,978 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 9)

TIME Completed the molecule generation in 144.2s.
TIME changed dir: 0.0s
Generated 47 conformers. 
Removed 39 conformers. 
TIME Completed the molecule generation in 124.6s.
TIME changed dir: 0.0s
Generated 42 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]Optimising conformer:  12%|██▉                    | 1/8 [00:03<00:24,  3.52s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:07<00:24,  4.03s/it]Optimising conformer:  38%|████████▋              | 3/8 [00:10<00:16,  3.31s/it]Optimising conformer:  50%|███████████▌           | 4/8 [00:12<00:11,  2.99s/it]Optimising conformer:  62%|██████████████▍        | 5/8 [00:18<00:11,  3.91s/it]Optimising conformer:  75%|█████████████████▎     | 6/8 [00:22<00:07,  4.00s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:26<00:04,  4.05s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:29<00:00,  3.58s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:29<00:00,  3.67s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 148.0s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s]Optimising conformer:   8%|█▋                    | 1/13 [00:03<00:37,  3.09s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:06<00:37,  3.40s/it]Optimising conformer:  23%|█████                 | 3/13 [00:09<00:32,  3.24s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:12<00:27,  3.05s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:14<00:22,  2.81s/it]Optimising conformer:  46%|██████████▏           | 6/13 [00:17<00:19,  2.73s/it]Optimising conformer:  54%|███████████▊          | 7/13 [00:20<00:17,  2.97s/it]Optimising conformer:  62%|█████████████▌        | 8/13 [00:25<00:17,  3.56s/it]Optimising conformer:  69%|███████████████▏      | 9/13 [00:29<00:14,  3.56s/it]Optimising conformer:  77%|████████████████▏    | 10/13 [00:30<00:08,  2.96s/it]Optimising conformer:  85%|█████████████████▊   | 11/13 [00:36<00:07,  3.84s/it]Optimising conformer:  92%|███████████████████▍ | 12/13 [00:38<00:03,  3.23s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:41<00:00,  3.25s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:41<00:00,  3.22s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 08:01:23,600 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.02s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:01:23,600 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 6.02s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:09,535 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:09,535 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.25s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:31:35,142 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.174:39811
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.174:39811 after 30 s
2024-02-01 08:31:35,142 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.174:39811
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.174:39811 after 30 s
2024-02-01 08:35:38,016 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:35:38,016 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:08,026 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:08,026 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:38,794 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:38,794 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:36:47,090 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 08:36:48,948 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

TIME Completed the molecule generation in 202.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 5 conformers. 
Generated 29 conformers. 
Removed 11 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]Optimising conformer:  33%|███████▋               | 1/3 [00:02<00:05,  2.62s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:09<00:04,  4.86s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:13<00:00,  4.55s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:13<00:00,  4.41s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/18 [00:00<?, ?it/s]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:   6%|█▏                    | 1/18 [00:03<00:53,  3.16s/it]Optimising conformer:  11%|██▍                   | 2/18 [00:05<00:42,  2.64s/it]Optimising conformer:  17%|███▋                  | 3/18 [00:07<00:32,  2.19s/it]/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:  22%|████▉                 | 4/18 [00:09<00:29,  2.14s/it]Optimising conformer:  28%|██████                | 5/18 [00:11<00:28,  2.19s/it]Optimising conformer:  33%|███████▎              | 6/18 [00:16<00:36,  3.00s/it]Optimising conformer:  39%|████████▌             | 7/18 [00:18<00:30,  2.74s/it]Optimising conformer:  44%|█████████▊            | 8/18 [00:20<00:26,  2.61s/it]Optimising conformer:  50%|███████████           | 9/18 [00:22<00:21,  2.43s/it]Optimising conformer:  56%|███████████▋         | 10/18 [00:24<00:18,  2.33s/it]TIME Completed the molecule generation in 60.3s.
TIME changed dir: 0.0s
Generated 4 conformers. 
Removed 0 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s][AOptimising conformer:  61%|████████████▊        | 11/18 [00:27<00:16,  2.39s/it]
Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:10,  3.58s/it][AOptimising conformer:  67%|██████████████       | 12/18 [00:29<00:14,  2.41s/it]
Optimising conformer:  50%|███████████▌           | 2/4 [00:06<00:06,  3.27s/it][AOptimising conformer:  72%|███████████████▏     | 13/18 [00:33<00:14,  2.90s/it]
Optimising conformer:  75%|█████████████████▎     | 3/4 [00:08<00:02,  2.75s/it][A
Optimising conformer: 100%|███████████████████████| 4/4 [00:10<00:00,  2.39s/it][AOptimising conformer: 100%|███████████████████████| 4/4 [00:10<00:00,  2.65s/it]
Optimising conformer:  78%|████████████████▎    | 14/18 [00:38<00:13,  3.38s/it]Optimising conformer:  83%|█████████████████▌   | 15/18 [00:40<00:08,  3.00s/it]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  89%|██████████████████▋  | 16/18 [00:43<00:05,  2.99s/it]Optimising conformer:  94%|███████████████████▊ | 17/18 [00:45<00:02,  2.66s/it]Optimising conformer: 100%|█████████████████████| 18/18 [00:47<00:00,  2.44s/it]Optimising conformer: 100%|█████████████████████| 18/18 [00:47<00:00,  2.62s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 38.7s.
TIME changed dir: 0.0s
Generated 23 conformers. 
Removed 10 conformers. 
TIME Completed the molecule generation in 116.7s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s]Optimising conformer:   8%|█▋                    | 1/13 [00:05<01:02,  5.18s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:09<00:52,  4.76s/it]Optimising conformer:  23%|█████                 | 3/13 [00:11<00:33,  3.33s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:13<00:24,  2.73s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:15<00:21,  2.73s/it]Optimising conformer:  46%|██████████▏           | 6/13 [00:17<00:16,  2.33s/it]Optimising conformer:  54%|███████████▊          | 7/13 [00:19<00:13,  2.32s/it]Optimising conformer:  62%|█████████████▌        | 8/13 [00:20<00:09,  1.95s/it]Optimising conformer:  69%|███████████████▏      | 9/13 [00:22<00:07,  1.89s/it]Optimising conformer:  77%|████████████████▏    | 10/13 [00:27<00:08,  2.91s/it]Optimising conformer:  85%|█████████████████▊   | 11/13 [00:30<00:06,  3.00s/it]Optimising conformer:  92%|███████████████████▍ | 12/13 [00:32<00:02,  2.58s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:33<00:00,  2.16s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:33<00:00,  2.60s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME changed dir: 0.0s
Generated 13 conformers. 
Removed 9 conformers. 
TIME Completed the molecule generation in 73.3s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:02<00:06,  2.24s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:03<00:03,  1.62s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:05<00:01,  1.63s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:06<00:00,  1.60s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:06<00:00,  1.66s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 89.7s.
TIME changed dir: 0.0s
Generated 7 conformers. 
Removed 3 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:02<00:07,  2.34s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:04<00:04,  2.15s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:05<00:01,  1.73s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:08<00:00,  2.21s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:08<00:00,  2.13s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 09:04:52,422 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.01s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:04:52,422 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.01s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,399 - distributed.core - INFO - Event loop was unresponsive in Worker for 3.12s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:10,399 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 3.12s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:23:13,081 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:34378
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:34378 after 30 s
2024-02-01 09:23:13,081 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:34378
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:34378 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 41.3s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 23 conformers. 
Removed 17 conformers. 
Generated 8 conformers. 
Removed 3 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s]Optimising conformer:  17%|███▊                   | 1/6 [00:04<00:21,  4.28s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:08<00:17,  4.25s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:11<00:10,  3.48s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:13<00:06,  3.16s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:16<00:02,  2.89s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:18<00:00,  2.81s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:18<00:00,  3.14s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  20%|████▌                  | 1/5 [00:05<00:21,  5.27s/it]/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:  40%|█████████▏             | 2/5 [00:11<00:17,  5.93s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:15<00:10,  5.17s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:18<00:04,  4.02s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:20<00:00,  3.51s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:20<00:00,  4.16s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 09:25:28,317 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 09:25:30,185 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

TIME Completed the molecule generation in 77.1s.
TIME changed dir: 0.0s
Generated 20 conformers. 
Removed 14 conformers. 
TIME Completed the molecule generation in 102.5s.
TIME changed dir: 0.0s
Generated 26 conformers. 
Removed 19 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s]Optimising conformer:  17%|███▊                   | 1/6 [00:05<00:26,  5.24s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:08<00:16,  4.03s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:11<00:10,  3.42s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:21<00:11,  5.98s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:23<00:04,  4.67s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:25<00:00,  3.86s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:25<00:00,  4.28s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
Optimising conformer:  14%|███▎                   | 1/7 [00:04<00:26,  4.48s/it]Optimising conformer:  29%|██████▌                | 2/7 [00:05<00:13,  2.62s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:08<00:11,  2.87s/it]Optimising conformer:  57%|█████████████▏         | 4/7 [00:12<00:09,  3.02s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:13<00:04,  2.35s/it]Optimising conformer:  86%|███████████████████▋   | 6/7 [00:15<00:02,  2.37s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:18<00:00,  2.41s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:18<00:00,  2.61s/it]
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 104.8s.
TIME changed dir: 0.0s
Generated 35 conformers. 
Removed 22 conformers. 
TIME Completed the molecule generation in 76.1s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s]Optimising conformer:   8%|█▋                    | 1/13 [00:03<00:38,  3.17s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:05<00:27,  2.48s/it]Optimising conformer:  23%|█████                 | 3/13 [00:09<00:33,  3.35s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:11<00:25,  2.83s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:13<00:20,  2.52s/it]Optimising conformer:  46%|██████████▏           | 6/13 [00:15<00:16,  2.43s/it]Optimising conformer:  54%|███████████▊          | 7/13 [00:18<00:15,  2.52s/it]Optimising conformer:  62%|█████████████▌        | 8/13 [00:19<00:10,  2.13s/it]Optimising conformer:  69%|███████████████▏      | 9/13 [00:21<00:08,  2.13s/it]Optimising conformer:  77%|████████████████▏    | 10/13 [00:23<00:06,  2.09s/it]Optimising conformer:  85%|█████████████████▊   | 11/13 [00:26<00:04,  2.14s/it]Optimising conformer:  92%|███████████████████▍ | 12/13 [00:28<00:02,  2.15s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:29<00:00,  1.93s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:29<00:00,  2.29s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
slurmstepd: error: *** JOB 19912152 ON sb051 CANCELLED AT 2024-02-01T09:54:42 ***
