hostname sb057.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:e4 brd ff:ff:ff:ff:ff:ff inet 10.3.81.137/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8e4/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:e5 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:e6 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:e7 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f7:00 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.137/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.137/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f700/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f7:01 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-02-01 07:04:52,756 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.137:38832'
2024-02-01 07:04:54,705 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-0pwx6o6u', purging
2024-02-01 07:05:10,014 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.137:45688
2024-02-01 07:05:10,016 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.137:45688
2024-02-01 07:05:10,016 - distributed.worker - INFO -           Worker name:           SLURMCluster-211
2024-02-01 07:05:10,016 - distributed.worker - INFO -          dashboard at:          10.3.89.137:41376
2024-02-01 07:05:10,016 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.11:37020
2024-02-01 07:05:10,016 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:05:10,016 - distributed.worker - INFO -               Threads:                          2
2024-02-01 07:05:10,016 - distributed.worker - INFO -                Memory:                  20.49 GiB
2024-02-01 07:05:10,016 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-6c9z8jr4
2024-02-01 07:05:10,016 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:05:10,610 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.11:37020
2024-02-01 07:05:10,610 - distributed.worker - INFO - -------------------------------------------------
2024-02-01 07:05:10,611 - distributed.core - INFO - Starting established connection to tcp://10.3.88.11:37020
2024-02-01 07:09:07,281 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.79s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:29,866 - distributed.core - INFO - Event loop was unresponsive in Worker for 60.55s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 07:14:29,866 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 60.55s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
2024-02-01 07:15:55,784 [WARNING] [__init__.py:5] root: Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-02-01 07:16:02,504 - distributed.worker - WARNING - Compute Failed
Key:       evaluate-b66493f3-a957-43b0-b65d-59025c9dbb0e
Function:  evaluate
args:      (<rdkit.Chem.rdchem.Mol object at 0x2afbb19fec20>, 6, 'c1(c(nc(c(C(N(c2nc(c(n2C(c2c(c(nc(c2[H])[H])[H])[H])([H])[H])[H])[H])[H])([H])[H])c1[H])[H])[H])[H]', '/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rec_final.pdb', '/nobackup/nmb1063/sars-fegrow/gnina')
kwargs:    {}
Exception: 'RuntimeError("Can\'t redefine method: forward on class: __torch__.torchani.aev.AEVComputer (of Python compilation unit at: 0x2afbadd3d2d0)")'

2024-02-01 07:16:02,504 [WARNING] [worker.py:2352] distributed.worker: Compute Failed
Key:       evaluate-b66493f3-a957-43b0-b65d-59025c9dbb0e
Function:  evaluate
args:      (<rdkit.Chem.rdchem.Mol object at 0x2afbb19fec20>, 6, 'c1(c(nc(c(C(N(c2nc(c(n2C(c2c(c(nc(c2[H])[H])[H])[H])([H])[H])[H])[H])[H])([H])[H])c1[H])[H])[H])[H]', '/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rec_final.pdb', '/nobackup/nmb1063/sars-fegrow/gnina')
kwargs:    {}
Exception: 'RuntimeError("Can\'t redefine method: forward on class: __torch__.torchani.aev.AEVComputer (of Python compilation unit at: 0x2afbadd3d2d0)")'

TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 26 conformers. 
Removed 20 conformers. 
Generated 46 conformers. 
Removed 41 conformers. 
using ani2x
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME changed dir: 0.0s
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:  20%|████▌                  | 1/5 [00:06<00:27,  6.78s/it]Optimising conformer:  40%|█████████▏             | 2/5 [00:12<00:17,  5.97s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:17<00:11,  5.81s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:20<00:04,  4.61s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:26<00:00,  5.04s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:26<00:00,  5.28s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Generated 8 conformers. 
Removed 6 conformers. 
TIME Completed the molecule generation in 128.6s.
TIME changed dir: 0.0s
Generated 37 conformers. 
Removed 25 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer:  50%|███████████▌           | 1/2 [00:03<00:03,  3.84s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:08<00:00,  4.04s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:08<00:00,  4.01s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 07:17:31,022 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 07:17:33,203 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 3)

TIME Completed the molecule generation in 79.9s.
TIME changed dir: 0.0s
Generated 42 conformers. 
Removed 36 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/12 [00:00<?, ?it/s]Optimising conformer:   8%|█▊                    | 1/12 [00:05<00:58,  5.33s/it]Optimising conformer:  17%|███▋                  | 2/12 [00:12<01:04,  6.48s/it]Optimising conformer:  25%|█████▌                | 3/12 [00:14<00:39,  4.35s/it]Optimising conformer:  33%|███████▎              | 4/12 [00:21<00:43,  5.49s/it]Optimising conformer:  42%|█████████▏            | 5/12 [00:27<00:38,  5.56s/it]Optimising conformer:  50%|███████████           | 6/12 [00:29<00:26,  4.37s/it]Optimising conformer:  58%|████████████▊         | 7/12 [00:31<00:18,  3.60s/it]Optimising conformer:  67%|██████████████▋       | 8/12 [00:34<00:13,  3.34s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s][A
Optimising conformer:  17%|███▊                   | 1/6 [00:04<00:24,  4.95s/it][A
Optimising conformer:  33%|███████▋               | 2/6 [00:09<00:18,  4.61s/it][A
Optimising conformer:  50%|███████████▌           | 3/6 [00:11<00:10,  3.64s/it][A
Optimising conformer:  67%|███████████████▎       | 4/6 [00:14<00:06,  3.33s/it][AOptimising conformer:  75%|████████████████▌     | 9/12 [00:57<00:28,  9.53s/it]
Optimising conformer:  83%|███████████████████▏   | 5/6 [00:18<00:03,  3.46s/it][AOptimising conformer:  83%|█████████████████▌   | 10/12 [00:59<00:14,  7.28s/it]
Optimising conformer: 100%|███████████████████████| 6/6 [00:22<00:00,  3.67s/it][AOptimising conformer: 100%|███████████████████████| 6/6 [00:22<00:00,  3.74s/it]
Optimising conformer:  92%|███████████████████▎ | 11/12 [01:02<00:05,  5.91s/it]Optimising conformer: 100%|█████████████████████| 12/12 [01:06<00:00,  5.27s/it]Optimising conformer: 100%|█████████████████████| 12/12 [01:06<00:00,  5.52s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
2024-02-01 08:01:23,584 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:01:23,584 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.52s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:12,148 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:03:12,148 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.23s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 08:35:38,025 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:35:38,025 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:08,075 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:08,075 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.93:44896
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.93:44896 after 30 s
2024-02-01 08:36:38,617 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
2024-02-01 08:36:38,617 [ERROR] [worker.py:2115] distributed.worker: Worker stream died during communication: tcp://10.3.89.95:36040
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:36040 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 152.4s.
TIME Completed the molecule generation in 110.8s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 22 conformers. 
Removed 13 conformers. 
Generated 40 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/9 [00:00<?, ?it/s]Optimising conformer:  11%|██▌                    | 1/9 [00:04<00:34,  4.32s/it]Optimising conformer:  22%|█████                  | 2/9 [00:23<01:31, 13.09s/it]Optimising conformer:  33%|███████▋               | 3/9 [00:28<00:55,  9.31s/it]Optimising conformer:  44%|██████████▏            | 4/9 [00:31<00:34,  6.84s/it]Optimising conformer:  56%|████████████▊          | 5/9 [00:34<00:22,  5.65s/it]Optimising conformer:  67%|███████████████▎       | 6/9 [00:37<00:13,  4.60s/it]Optimising conformer:  78%|█████████████████▉     | 7/9 [00:41<00:08,  4.31s/it]Optimising conformer:  89%|████████████████████▍  | 8/9 [00:45<00:04,  4.20s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:50<00:00,  4.70s/it]Optimising conformer: 100%|███████████████████████| 9/9 [00:51<00:00,  5.67s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/11 [00:00<?, ?it/s]/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Optimising conformer:   9%|██                    | 1/11 [00:17<02:51, 17.12s/it]Optimising conformer:  18%|████                  | 2/11 [00:19<01:13,  8.20s/it]Optimising conformer:  27%|██████                | 3/11 [00:22<00:46,  5.81s/it]Optimising conformer:  36%|████████              | 4/11 [00:24<00:30,  4.40s/it]Optimising conformer:  45%|██████████            | 5/11 [00:26<00:21,  3.54s/it]Optimising conformer:  55%|████████████          | 6/11 [00:28<00:16,  3.21s/it]Optimising conformer:  64%|██████████████        | 7/11 [00:33<00:14,  3.60s/it]Optimising conformer:  73%|████████████████      | 8/11 [00:35<00:09,  3.04s/it]Optimising conformer:  82%|██████████████████    | 9/11 [00:40<00:07,  3.78s/it]Optimising conformer:  91%|███████████████████  | 10/11 [00:43<00:03,  3.44s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:46<00:00,  3.43s/it]Optimising conformer: 100%|█████████████████████| 11/11 [00:46<00:00,  4.24s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 102.0s.
TIME changed dir: 0.0s
Generated 9 conformers. 
Removed 1 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME Completed the molecule generation in 153.7s.
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]Optimising conformer:  12%|██▉                    | 1/8 [00:02<00:15,  2.27s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:03<00:09,  1.52s/it]Optimising conformer:  38%|████████▋              | 3/8 [00:05<00:09,  1.97s/it]Optimising conformer:  50%|███████████▌           | 4/8 [00:07<00:07,  1.82s/it]Optimising conformer:  62%|██████████████▍        | 5/8 [00:09<00:05,  1.79s/it]2024-02-01 08:39:26,672 - distributed.worker - WARNING - Compute Failed
Key:       evaluate-95545339-5be3-4eac-92d8-d182966954b9
Function:  evaluate
args:      (<rdkit.Chem.rdchem.Mol object at 0x2afc8676c4a0>, 6, '[H]c1nc([H])c([C@]2([H])C([H])([H])[C@@]3([H])N(OC([H])([H])C4([H])C([H])([H])C4([H])[H])[C@]([H])(C([H])([H])C3([H])[H])C2([H])[H])c([H])c1[H]', '/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rec_final.pdb', '/nobackup/nmb1063/sars-fegrow/gnina')
kwargs:    {}
Exception: "Exception('No Conformers')"

2024-02-01 08:39:26,672 [WARNING] [worker.py:2352] distributed.worker: Compute Failed
Key:       evaluate-95545339-5be3-4eac-92d8-d182966954b9
Function:  evaluate
args:      (<rdkit.Chem.rdchem.Mol object at 0x2afc8676c4a0>, 6, '[H]c1nc([H])c([C@]2([H])C([H])([H])[C@@]3([H])N(OC([H])([H])C4([H])C([H])([H])C4([H])[H])[C@]([H])(C([H])([H])C3([H])[H])C2([H])[H])c([H])c1[H]', '/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rec_final.pdb', '/nobackup/nmb1063/sars-fegrow/gnina')
kwargs:    {}
Exception: "Exception('No Conformers')"

Optimising conformer:  75%|█████████████████▎     | 6/8 [00:10<00:03,  1.80s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:12<00:01,  1.59s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:13<00:00,  1.40s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:13<00:00,  1.63s/it]
2024-02-01 09:04:51,912 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:04:51,912 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.30s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,235 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-02-01 09:05:13,235 [INFO] [core.py:595] distributed.core: Event loop was unresponsive in Worker for 5.63s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 09:22:58,659 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 13)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
2024-02-01 09:23:00,963 [WARNING] [rdkit_wrapper.py:3213] openff.toolkit.utils.rdkit_wrapper: Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Undefined chiral centers are:
 - Atom C (index 13)

TIME changed dir: 0.0s
Generated 28 conformers. 
Removed 28 conformers. 
Warning: no conformers so cannot optimise_in_receptor. Ignoring.
TIME Completed the molecule generation in 76.2s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 25 conformers. 
Removed 18 conformers. 
Generated 50 conformers. 
Removed 43 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s]Optimising conformer:  14%|███▎                   | 1/7 [00:05<00:34,  5.76s/it]Optimising conformer:  29%|██████▌                | 2/7 [00:12<00:30,  6.13s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:17<00:23,  5.92s/it]Optimising conformer:  57%|█████████████▏         | 4/7 [00:22<00:15,  5.27s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:26<00:09,  4.90s/it]Optimising conformer:  86%|███████████████████▋   | 6/7 [00:28<00:03,  3.82s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:30<00:00,  3.44s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:30<00:00,  4.39s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 134.6s.
TIME changed dir: 0.0s
Generated 10 conformers. 
Removed 2 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s]Optimising conformer:  12%|██▉                    | 1/8 [00:02<00:15,  2.16s/it]Optimising conformer:  25%|█████▊                 | 2/8 [00:03<00:08,  1.44s/it]Optimising conformer:  38%|████████▋              | 3/8 [00:04<00:06,  1.27s/it]Optimising conformer:  50%|███████████▌           | 4/8 [00:05<00:05,  1.46s/it]Optimising conformer:  62%|██████████████▍        | 5/8 [00:06<00:03,  1.29s/it]Optimising conformer:  75%|█████████████████▎     | 6/8 [00:08<00:02,  1.37s/it]Optimising conformer:  88%|████████████████████▏  | 7/8 [00:09<00:01,  1.30s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:10<00:00,  1.26s/it]Optimising conformer: 100%|███████████████████████| 8/8 [00:10<00:00,  1.34s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
TIME Completed the molecule generation in 36.1s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s]Optimising conformer:  14%|███▎                   | 1/7 [00:02<00:17,  2.95s/it]Optimising conformer:  29%|██████▌                | 2/7 [00:06<00:15,  3.03s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:09<00:12,  3.19s/it]Optimising conformer:  57%|█████████████▏         | 4/7 [00:12<00:09,  3.01s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:24<00:12,  6.24s/it]Optimising conformer:  86%|███████████████████▋   | 6/7 [00:28<00:05,  5.75s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:30<00:00,  4.39s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:30<00:00,  4.36s/it]
/mnt/storage/nobackup/nmb1063/code/gal/sars-cov-2-main-protease-al-study-combo1/rsearcher.py:89: UserWarning: The ligand was an array (SDF?). Using the first frame. 
  warnings.warn("The ligand was an array (SDF?). Using the first frame. ")
slurmstepd: error: *** JOB 19912170 ON sb057 CANCELLED AT 2024-02-01T09:54:44 ***
