hostname sb047.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:9c brd ff:ff:ff:ff:ff:ff inet 10.3.81.127/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c99c/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:9d brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:9e brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:9f brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f4:b0 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.127/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.127/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f4b0/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f4:b1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 07:55:55,237 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.127:40705'
2024-01-19 07:55:55,255 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.127:41462'
2024-01-19 07:55:57,035 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-lef91cpa', purging
2024-01-19 07:55:57,036 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-_lrx7re6', purging
2024-01-19 07:55:57,036 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-m2vg2fm0', purging
2024-01-19 07:55:57,036 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-z1fedxdc', purging
2024-01-19 07:55:57,036 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-kreuf23p', purging
2024-01-19 07:55:57,037 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-vgnioeo1', purging
2024-01-19 07:55:59,906 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.127:39723
2024-01-19 07:55:59,906 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.127:44985
2024-01-19 07:55:59,907 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.127:39723
2024-01-19 07:55:59,907 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.127:44985
2024-01-19 07:55:59,907 - distributed.worker - INFO -           Worker name:         SLURMCluster-419-1
2024-01-19 07:55:59,907 - distributed.worker - INFO -           Worker name:         SLURMCluster-419-0
2024-01-19 07:55:59,907 - distributed.worker - INFO -          dashboard at:          10.3.89.127:38405
2024-01-19 07:55:59,907 - distributed.worker - INFO -          dashboard at:          10.3.89.127:45314
2024-01-19 07:55:59,907 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:55:59,907 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:55:59,907 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,907 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,907 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:55:59,907 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:55:59,907 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:55:59,907 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:55:59,907 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-jog4c_6l
2024-01-19 07:55:59,907 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-7r1efkbc
2024-01-19 07:55:59,907 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,907 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,943 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:55:59,943 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,943 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 07:55:59,956 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:55:59,956 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:59,956 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:03:39,334 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:40469
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:40469 after 30 s
2024-01-19 08:03:39,381 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:44379
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:44379 after 30 s
2024-01-19 08:03:59,962 - distributed.core - INFO - Event loop was unresponsive in Worker for 20.20s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 08:04:05,881 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.82s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-01-19 08:05:17,508 - distributed.nanny - INFO - Worker process 30608 was killed by signal 11
2024-01-19 08:05:17,513 - distributed.nanny - WARNING - Restarting worker
TIME changed dir: 0.0s
Generated 35 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/6 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
2024-01-19 08:05:21,973 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.127:38725
2024-01-19 08:05:21,974 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.127:38725
2024-01-19 08:05:21,974 - distributed.worker - INFO -           Worker name:         SLURMCluster-419-1
2024-01-19 08:05:21,974 - distributed.worker - INFO -          dashboard at:          10.3.89.127:41184
2024-01-19 08:05:21,974 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:05:21,974 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:21,974 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:05:21,974 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:05:21,974 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-wq9co1b5
2024-01-19 08:05:21,974 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:22,007 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:05:22,007 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:22,007 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
Optimising conformer:  17%|███▊                   | 1/6 [00:03<00:18,  3.73s/it]Optimising conformer:  33%|███████▋               | 2/6 [00:05<00:10,  2.65s/it]Optimising conformer:  50%|███████████▌           | 3/6 [00:07<00:06,  2.30s/it]Optimising conformer:  67%|███████████████▎       | 4/6 [00:09<00:04,  2.14s/it]Optimising conformer:  83%|███████████████████▏   | 5/6 [00:11<00:02,  2.05s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:13<00:00,  2.01s/it]Optimising conformer: 100%|███████████████████████| 6/6 [00:13<00:00,  2.20s/it]
2024-01-19 09:24:02,079 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:02,101 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.127:38725. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:02,111 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.127:41462'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:02,119 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.127:51672 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:24:02,129 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:04,138 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-19 09:24:05,250 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.127:41462'. Reason: nanny-close-gracefully
2024-01-19 09:24:32,215 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.127:51628 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:38,623 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:38,626 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.127:44985. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:38,629 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.127:40705'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:38,636 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:38,656 - distributed.nanny - INFO - Worker closed
TIME Completed the molecule generation in 97.4s.
2024-01-19 09:24:43,752 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.127:40705'. Reason: nanny-close-gracefully
2024-01-19 09:24:43,756 - distributed.dask_worker - INFO - End worker
