hostname sb030.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:e8 brd ff:ff:ff:ff:ff:ff inet 10.3.81.110/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c9e8/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:e9 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:ea brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:eb brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:10 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.110/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.110/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f310/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:11 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 07:55:54,090 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.110:33510'
2024-01-19 07:55:54,103 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.110:41596'
2024-01-19 07:55:58,452 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.110:45080
2024-01-19 07:55:58,452 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.110:33774
2024-01-19 07:55:58,455 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.110:45080
2024-01-19 07:55:58,455 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.110:33774
2024-01-19 07:55:58,455 - distributed.worker - INFO -           Worker name:         SLURMCluster-378-1
2024-01-19 07:55:58,455 - distributed.worker - INFO -           Worker name:         SLURMCluster-378-0
2024-01-19 07:55:58,455 - distributed.worker - INFO -          dashboard at:          10.3.89.110:39592
2024-01-19 07:55:58,455 - distributed.worker - INFO -          dashboard at:          10.3.89.110:39700
2024-01-19 07:55:58,455 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:55:58,455 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:55:58,455 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,455 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,455 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:55:58,455 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:55:58,455 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:55:58,455 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:55:58,455 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-afsp2mbq
2024-01-19 07:55:58,455 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-lscu9f0r
2024-01-19 07:55:58,455 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,455 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,503 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:55:58,503 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,504 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 07:55:58,514 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:55:58,514 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:55:58,515 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:04:05,241 - distributed.core - INFO - Event loop was unresponsive in Worker for 5.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 29 conformers. 
Removed 22 conformers. 
Generated 26 conformers. 
Removed 13 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/13 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:   8%|█▋                    | 1/13 [00:04<00:49,  4.12s/it]Optimising conformer:  15%|███▍                  | 2/13 [00:06<00:35,  3.25s/it]Optimising conformer:  23%|█████                 | 3/13 [00:08<00:27,  2.72s/it]Optimising conformer:  31%|██████▊               | 4/13 [00:11<00:25,  2.80s/it]Optimising conformer:  38%|████████▍             | 5/13 [00:13<00:19,  2.50s/it]Optimising conformer:  46%|██████████▏           | 6/13 [00:16<00:18,  2.59s/it]Optimising conformer:  54%|███████████▊          | 7/13 [00:19<00:15,  2.65s/it]Optimising conformer:  62%|█████████████▌        | 8/13 [00:22<00:13,  2.71s/it]Optimising conformer:  69%|███████████████▏      | 9/13 [00:24<00:10,  2.55s/it]Optimising conformer:  77%|████████████████▏    | 10/13 [00:26<00:07,  2.57s/it]Optimising conformer:  85%|█████████████████▊   | 11/13 [00:29<00:04,  2.47s/it]Optimising conformer:  92%|███████████████████▍ | 12/13 [00:31<00:02,  2.49s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:34<00:00,  2.44s/it]Optimising conformer: 100%|█████████████████████| 13/13 [00:34<00:00,  2.62s/it]
TIME Completed the molecule generation in 100.6s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s]Optimising conformer:  14%|███▎                   | 1/7 [00:03<00:21,  3.55s/it]Optimising conformer:  29%|██████▌                | 2/7 [00:11<00:31,  6.35s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:15<00:20,  5.17s/it]Optimising conformer:  57%|█████████████▏         | 4/7 [00:17<00:11,  3.93s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:18<00:05,  2.97s/it]Optimising conformer:  86%|███████████████████▋   | 6/7 [00:20<00:02,  2.63s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:22<00:00,  2.40s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:22<00:00,  3.26s/it]
2024-01-19 09:24:30,676 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.110:59352 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:30,676 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.110:59358 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:50,066 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:50,070 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.110:33774. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:50,074 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.110:33510'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:50,084 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:50,091 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:50,130 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:50,131 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.110:45080. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:50,133 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.110:41596'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:50,135 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:50,141 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:52,100 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 161.6s.
2024-01-19 09:24:52,581 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.110:41596'. Reason: nanny-close-gracefully
2024-01-19 09:24:54,748 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.110:33510'. Reason: nanny-close-gracefully
2024-01-19 09:24:54,754 - distributed.dask_worker - INFO - End worker
