hostname sb044.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:ac brd ff:ff:ff:ff:ff:ff inet 10.3.81.124/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8ac/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:ad brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:ae brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:af brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:30 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.124/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.124/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f330/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f3:31 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 07:59:30,033 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.124:46015'
2024-01-19 07:59:30,096 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.124:39550'
2024-01-19 07:59:31,828 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-xvjfzkmk', purging
2024-01-19 07:59:31,829 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-me5q62my', purging
2024-01-19 07:59:31,829 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-p71ak5q0', purging
2024-01-19 07:59:31,829 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-6k5rc8fd', purging
2024-01-19 07:59:45,077 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.124:39253
2024-01-19 07:59:45,077 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.124:44489
2024-01-19 07:59:45,079 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.124:39253
2024-01-19 07:59:45,079 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.124:44489
2024-01-19 07:59:45,079 - distributed.worker - INFO -           Worker name:          SLURMCluster-35-1
2024-01-19 07:59:45,079 - distributed.worker - INFO -           Worker name:          SLURMCluster-35-0
2024-01-19 07:59:45,079 - distributed.worker - INFO -          dashboard at:          10.3.89.124:39680
2024-01-19 07:59:45,079 - distributed.worker - INFO -          dashboard at:          10.3.89.124:42278
2024-01-19 07:59:45,079 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:59:45,079 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 07:59:45,079 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,079 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,079 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:59:45,079 - distributed.worker - INFO -               Threads:                          2
2024-01-19 07:59:45,079 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:59:45,079 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 07:59:45,080 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-lippns9w
2024-01-19 07:59:45,080 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-hs_bz5f3
2024-01-19 07:59:45,080 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,080 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,120 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:59:45,121 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,121 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 07:59:45,124 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 07:59:45,124 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 07:59:45,125 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:04:07,602 - distributed.core - INFO - Event loop was unresponsive in Worker for 7.44s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-01-19 08:05:35,596 - distributed.nanny - INFO - Worker process 11050 was killed by signal 11
2024-01-19 08:05:35,601 - distributed.nanny - WARNING - Restarting worker
2024-01-19 08:05:39,082 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.124:45668
2024-01-19 08:05:39,083 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.124:45668
2024-01-19 08:05:39,083 - distributed.worker - INFO -           Worker name:          SLURMCluster-35-0
2024-01-19 08:05:39,083 - distributed.worker - INFO -          dashboard at:          10.3.89.124:46713
2024-01-19 08:05:39,083 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:05:39,083 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:39,083 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:05:39,083 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:05:39,084 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-o7eusijx
2024-01-19 08:05:39,084 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:39,120 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:05:39,120 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:05:39,122 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 09:24:30,685 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:30,706 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.124:45668. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:30,709 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.124:46015'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:30,713 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.124:60762 remote=tcp://10.3.88.12:42763>: Stream is closed
2024-01-19 09:24:30,713 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:31,581 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.124:60738 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:32,905 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.124:46015'. Reason: nanny-close-gracefully
2024-01-19 09:24:36,701 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:36,704 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.124:39253. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,708 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.124:39550'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,711 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:36,731 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:38,733 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-19 09:24:38,890 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.124:39550'. Reason: nanny-close-gracefully
2024-01-19 09:24:38,891 - distributed.dask_worker - INFO - End worker
