hostname sb033.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:61:07:82 brd ff:ff:ff:ff:ff:ff inet 10.3.81.113/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe61:782/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:83 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:84 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:85 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:40 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.113/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.113/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f640/64 scope link valid_lft forever preferred_lft forever 7: ib1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 4092 qdisc pfifo_fast state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f6:41 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 08:21:00,127 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.113:37621'
2024-01-19 08:21:00,154 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.113:44882'
2024-01-19 08:21:03,371 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-nbdb7r6m', purging
2024-01-19 08:21:03,372 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-587xpusn', purging
2024-01-19 08:21:03,373 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-h5uz_ogf', purging
2024-01-19 08:21:03,373 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-53sbgn_2', purging
2024-01-19 08:21:03,373 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-184n3jbt', purging
2024-01-19 08:21:03,374 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-s9tj0_l3', purging
2024-01-19 08:21:03,374 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-ct9nkeet', purging
2024-01-19 08:21:03,374 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-63uz4aim', purging
2024-01-19 08:21:03,374 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-e01dczhu', purging
2024-01-19 08:21:03,375 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-7b_qw8k3', purging
2024-01-19 08:21:08,174 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.113:33533
2024-01-19 08:21:08,174 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.113:37012
2024-01-19 08:21:08,175 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.113:33533
2024-01-19 08:21:08,175 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.113:37012
2024-01-19 08:21:08,175 - distributed.worker - INFO -           Worker name:         SLURMCluster-451-1
2024-01-19 08:21:08,175 - distributed.worker - INFO -           Worker name:         SLURMCluster-451-0
2024-01-19 08:21:08,175 - distributed.worker - INFO -          dashboard at:          10.3.89.113:46670
2024-01-19 08:21:08,175 - distributed.worker - INFO -          dashboard at:          10.3.89.113:46873
2024-01-19 08:21:08,175 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:21:08,175 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:21:08,175 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,175 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,175 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:21:08,175 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:21:08,175 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:21:08,175 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:21:08,175 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-0vimvx4c
2024-01-19 08:21:08,175 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-m34oe8za
2024-01-19 08:21:08,175 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,175 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,277 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:21:08,277 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,278 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:21:08,287 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:21:08,287 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:21:08,287 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 09:24:32,321 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.113:58948 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:32,321 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.113:58954 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:59,841 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:59,841 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:59,842 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.113:33533. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:59,842 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.113:37012. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:59,845 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.113:44882'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:59,846 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.113:37621'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:59,849 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:59,849 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:59,867 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:59,868 - distributed.nanny - INFO - Worker closed
2024-01-19 09:25:01,869 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-19 09:25:02,226 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.113:44882'. Reason: nanny-close-gracefully
2024-01-19 09:25:02,228 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.113:37621'. Reason: nanny-close-gracefully
2024-01-19 09:25:02,229 - distributed.dask_worker - INFO - End worker
