hostname sb045.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:74:c8:c0 brd ff:ff:ff:ff:ff:ff inet 10.3.81.125/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe74:c8c0/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c1 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c2 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:74:c8:c3 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f2:e0 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.125/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.125/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f2e0/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f2:e1 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 08:00:40,431 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.125:39418'
2024-01-19 08:00:40,625 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.125:39853'
2024-01-19 08:00:42,168 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-9e26yf_o', purging
2024-01-19 08:00:42,168 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-cl9k3682', purging
2024-01-19 08:00:42,169 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-pnpr52xt', purging
2024-01-19 08:00:42,169 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-ejg6vyed', purging
2024-01-19 08:00:42,169 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-6o6it2g2', purging
2024-01-19 08:00:42,169 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-dwgmqogr', purging
2024-01-19 08:00:42,170 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-3t579ixv', purging
2024-01-19 08:00:42,170 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-nwjq1d0s', purging
2024-01-19 08:00:42,170 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-zy43sce2', purging
2024-01-19 08:00:42,170 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-n0v8v_t4', purging
2024-01-19 08:01:01,853 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.125:36847
2024-01-19 08:01:01,853 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.125:38904
2024-01-19 08:01:01,854 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.125:36847
2024-01-19 08:01:01,854 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.125:38904
2024-01-19 08:01:01,854 - distributed.worker - INFO -           Worker name:         SLURMCluster-402-0
2024-01-19 08:01:01,854 - distributed.worker - INFO -           Worker name:         SLURMCluster-402-1
2024-01-19 08:01:01,854 - distributed.worker - INFO -          dashboard at:          10.3.89.125:43809
2024-01-19 08:01:01,854 - distributed.worker - INFO -          dashboard at:          10.3.89.125:45246
2024-01-19 08:01:01,854 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:01:01,854 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 08:01:01,854 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,854 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,854 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:01:01,854 - distributed.worker - INFO -               Threads:                          2
2024-01-19 08:01:01,854 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:01:01,854 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 08:01:01,854 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-_828c6is
2024-01-19 08:01:01,854 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-cbiboikq
2024-01-19 08:01:01,854 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,854 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,925 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:01:01,925 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,926 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:01:01,933 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 08:01:01,933 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 08:01:01,933 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 08:03:39,299 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:40469
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:40469 after 30 s
2024-01-19 08:03:39,380 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:44379
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:44379 after 30 s
2024-01-19 08:03:59,966 - distributed.core - INFO - Event loop was unresponsive in Worker for 20.18s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
Warning (not error because allow_undefined_stereo=True): RDMol has unspecified stereochemistry. Bonds with undefined stereochemistry are:
 - Bond 1 (atoms 1-2 of element (C-C)

/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 31 conformers. 
Generated 29 conformers. 
Removed 14 conformers. 
Removed 22 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/17 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:   6%|█▎                    | 1/17 [00:04<01:14,  4.65s/it]Optimising conformer:  12%|██▌                   | 2/17 [00:07<00:52,  3.52s/it]Optimising conformer:  18%|███▉                  | 3/17 [00:09<00:43,  3.10s/it]using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s][A
Optimising conformer:  14%|███▎                   | 1/7 [00:03<00:18,  3.01s/it][AOptimising conformer:  24%|█████▏                | 4/17 [00:13<00:43,  3.33s/it]
Optimising conformer:  29%|██████▌                | 2/7 [00:05<00:14,  2.94s/it][AOptimising conformer:  29%|██████▍               | 5/17 [00:16<00:36,  3.05s/it]
Optimising conformer:  43%|█████████▊             | 3/7 [00:09<00:12,  3.10s/it][AOptimising conformer:  35%|███████▊              | 6/17 [00:19<00:35,  3.19s/it]
Optimising conformer:  57%|█████████████▏         | 4/7 [00:11<00:08,  2.81s/it][AOptimising conformer:  41%|█████████             | 7/17 [00:23<00:34,  3.48s/it]
Optimising conformer:  71%|████████████████▍      | 5/7 [00:13<00:05,  2.54s/it][A
Optimising conformer:  86%|███████████████████▋   | 6/7 [00:15<00:02,  2.36s/it][AOptimising conformer:  47%|██████████▎           | 8/17 [00:27<00:30,  3.42s/it]
Optimising conformer: 100%|███████████████████████| 7/7 [00:18<00:00,  2.47s/it][AOptimising conformer: 100%|███████████████████████| 7/7 [00:18<00:00,  2.62s/it]
Optimising conformer:  53%|███████████▋          | 9/17 [00:29<00:25,  3.21s/it]Optimising conformer:  59%|████████████▎        | 10/17 [00:32<00:21,  3.08s/it]Optimising conformer:  65%|█████████████▌       | 11/17 [00:36<00:20,  3.45s/it]Optimising conformer:  71%|██████████████▊      | 12/17 [00:39<00:15,  3.14s/it]Optimising conformer:  76%|████████████████     | 13/17 [00:43<00:13,  3.36s/it]Optimising conformer:  82%|█████████████████▎   | 14/17 [00:45<00:09,  3.11s/it]Optimising conformer:  88%|██████████████████▌  | 15/17 [00:48<00:06,  3.15s/it]Optimising conformer:  94%|███████████████████▊ | 16/17 [00:51<00:02,  2.91s/it]Optimising conformer: 100%|█████████████████████| 17/17 [00:55<00:00,  3.23s/it]Optimising conformer: 100%|█████████████████████| 17/17 [00:55<00:00,  3.25s/it]
2024-01-19 09:24:30,931 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.125:44896 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:31,187 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.125:44892 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:40,604 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:40,605 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.125:36847. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:40,603 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:40,608 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.125:38904. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:40,610 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.125:39418'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:40,612 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.125:39853'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:40,624 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:40,619 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:40,629 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:40,629 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:42,639 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 77.9s.
TIME Completed the molecule generation in 100.7s.
2024-01-19 09:24:43,221 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.125:39418'. Reason: nanny-close-gracefully
2024-01-19 09:24:45,881 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.125:39853'. Reason: nanny-close-gracefully
2024-01-19 09:24:45,890 - distributed.dask_worker - INFO - End worker
