hostname sb032.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:34:c9:a4 brd ff:ff:ff:ff:ff:ff inet 10.3.81.112/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe34:c9a4/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:a5 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:a6 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:34:c9:a7 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:10 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.112/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.97.112/22 brd 10.3.99.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::3abc:103:4c:f510/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:38:bc:01:03:00:4c:f5:11 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 06:03:32,432 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.112:36190'
2024-01-19 06:03:32,478 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.112:43947'
2024-01-19 06:03:34,814 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-wqi96l51', purging
2024-01-19 06:03:34,815 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-pdft15n4', purging
2024-01-19 06:03:44,494 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.112:46077
2024-01-19 06:03:44,495 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.112:46077
2024-01-19 06:03:44,495 - distributed.worker - INFO -           Worker name:         SLURMCluster-280-0
2024-01-19 06:03:44,495 - distributed.worker - INFO -          dashboard at:          10.3.89.112:43493
2024-01-19 06:03:44,495 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,495 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,495 - distributed.worker - INFO -               Threads:                          2
2024-01-19 06:03:44,495 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 06:03:44,495 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-xs0waqv_
2024-01-19 06:03:44,495 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,495 - distributed.worker - INFO -       Start worker at:    tcp://10.3.89.112:41457
2024-01-19 06:03:44,495 - distributed.worker - INFO -          Listening to:    tcp://10.3.89.112:41457
2024-01-19 06:03:44,496 - distributed.worker - INFO -           Worker name:         SLURMCluster-280-1
2024-01-19 06:03:44,496 - distributed.worker - INFO -          dashboard at:          10.3.89.112:40069
2024-01-19 06:03:44,496 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,496 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,496 - distributed.worker - INFO -               Threads:                          2
2024-01-19 06:03:44,496 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 06:03:44,496 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-pm41ioim
2024-01-19 06:03:44,496 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,561 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,561 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,562 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 06:03:44,566 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,566 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,567 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 06:16:02,881 - distributed.core - INFO - Event loop was unresponsive in Worker for 35.76s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 06:16:02,896 - distributed.core - INFO - Event loop was unresponsive in Worker for 35.87s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 15 conformers. 
Removed 8 conformers. 
Generated 15 conformers. 
Removed 10 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/7 [00:00<?, ?it/s][W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  14%|███▎                   | 1/7 [00:04<00:24,  4.09s/it]failed to equip `nnpops` with error: No module named 'NNPOps'

Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s][AOptimising conformer:  29%|██████▌                | 2/7 [00:06<00:14,  2.81s/it]Optimising conformer:  43%|█████████▊             | 3/7 [00:07<00:09,  2.33s/it]
Optimising conformer:  20%|████▌                  | 1/5 [00:05<00:21,  5.30s/it][AOptimising conformer:  57%|█████████████▏         | 4/7 [00:11<00:08,  2.91s/it]Optimising conformer:  71%|████████████████▍      | 5/7 [00:13<00:05,  2.51s/it]
Optimising conformer:  40%|█████████▏             | 2/5 [00:08<00:12,  4.30s/it][A/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Optimising conformer:  86%|███████████████████▋   | 6/7 [00:16<00:02,  2.77s/it]Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

Optimising conformer:  60%|█████████████▊         | 3/5 [00:13<00:08,  4.43s/it][AOptimising conformer: 100%|███████████████████████| 7/7 [00:20<00:00,  3.05s/it]Optimising conformer: 100%|███████████████████████| 7/7 [00:20<00:00,  2.89s/it]

Optimising conformer:  80%|██████████████████▍    | 4/5 [00:16<00:03,  3.94s/it][ATIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 16 conformers. 
Generated 22 conformers. 
Removed 13 conformers. 
Removed 18 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/3 [00:00<?, ?it/s]
Optimising conformer: 100%|███████████████████████| 5/5 [00:19<00:00,  3.65s/it][AOptimising conformer: 100%|███████████████████████| 5/5 [00:19<00:00,  3.96s/it]
[W BinaryOps.cpp:601] Warning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (function operator())
Optimising conformer:  33%|███████▋               | 1/3 [00:06<00:12,  6.20s/it]Optimising conformer:  67%|███████████████▎       | 2/3 [00:09<00:04,  4.54s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:11<00:00,  3.46s/it]Optimising conformer: 100%|███████████████████████| 3/3 [00:11<00:00,  3.92s/it]
TIME Completed the molecule generation in 81.2s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:02<00:08,  2.87s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:05<00:05,  2.94s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:08<00:03,  3.03s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:14<00:00,  3.85s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:14<00:00,  3.53s/it]
2024-01-19 07:42:07,115 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:35361
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:35361 after 30 s
2024-01-19 07:42:07,203 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.95:33957
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.95:33957 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 115.4s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 28 conformers. 
Generated 40 conformers. 
Removed 20 conformers. 
Removed 21 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/19 [00:00<?, ?it/s]
Optimising conformer:   0%|                               | 0/8 [00:00<?, ?it/s][A
Optimising conformer:  12%|██▉                    | 1/8 [00:03<00:22,  3.28s/it][A
Optimising conformer:  25%|█████▊                 | 2/8 [00:05<00:14,  2.36s/it][AOptimising conformer:   5%|█▏                    | 1/19 [00:05<01:39,  5.51s/it]Optimising conformer:  11%|██▎                   | 2/19 [00:07<00:59,  3.52s/it]Optimising conformer:  16%|███▍                  | 3/19 [00:09<00:46,  2.93s/it]Optimising conformer:  21%|████▋                 | 4/19 [00:12<00:42,  2.80s/it]Optimising conformer:  26%|█████▊                | 5/19 [00:14<00:36,  2.62s/it]Optimising conformer:  32%|██████▉               | 6/19 [00:17<00:34,  2.68s/it]
Optimising conformer:  38%|████████▋              | 3/8 [00:17<00:35,  7.13s/it][A
Optimising conformer:  50%|███████████▌           | 4/8 [00:19<00:20,  5.08s/it][AOptimising conformer:  37%|████████              | 7/19 [00:22<00:40,  3.39s/it]
Optimising conformer:  62%|██████████████▍        | 5/8 [00:22<00:12,  4.20s/it][AOptimising conformer:  42%|█████████▎            | 8/19 [00:24<00:32,  2.92s/it]
Optimising conformer:  75%|█████████████████▎     | 6/8 [00:24<00:07,  3.59s/it][A
Optimising conformer:  88%|████████████████████▏  | 7/8 [00:29<00:03,  3.96s/it][ATIME Completed the molecule generation in 70.0s.
TIME Completed the molecule generation in 70.2s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 17 conformers. 
Generated 21 conformers. 
Removed 12 conformers. 
Removed 16 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]Optimising conformer:  47%|██████████▍           | 9/19 [00:30<00:38,  3.88s/it]
Optimising conformer: 100%|███████████████████████| 8/8 [00:32<00:00,  3.54s/it][AOptimising conformer: 100%|███████████████████████| 8/8 [00:32<00:00,  4.02s/it]
Optimising conformer:  53%|███████████          | 10/19 [00:33<00:31,  3.53s/it]Optimising conformer:  20%|████▌                  | 1/5 [00:04<00:16,  4.00s/it]Optimising conformer:  40%|█████████▏             | 2/5 [00:06<00:10,  3.40s/it]Optimising conformer:  58%|████████████▏        | 11/19 [00:39<00:35,  4.41s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:11<00:07,  3.77s/it]Optimising conformer:  63%|█████████████▎       | 12/19 [00:44<00:31,  4.53s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:14<00:03,  3.72s/it]Optimising conformer:  68%|██████████████▎      | 13/19 [00:46<00:22,  3.71s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:18<00:00,  3.53s/it]Optimising conformer: 100%|███████████████████████| 5/5 [00:18<00:00,  3.61s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/5 [00:00<?, ?it/s]Optimising conformer:  74%|███████████████▍     | 14/19 [00:51<00:20,  4.17s/it]Optimising conformer:  20%|████▌                  | 1/5 [00:04<00:18,  4.66s/it]Optimising conformer:  79%|████████████████▌    | 15/19 [00:55<00:16,  4.08s/it]Optimising conformer:  84%|█████████████████▋   | 16/19 [00:56<00:10,  3.34s/it]Optimising conformer:  89%|██████████████████▊  | 17/19 [01:00<00:07,  3.52s/it]Optimising conformer:  95%|███████████████████▉ | 18/19 [01:05<00:03,  3.97s/it]Optimising conformer: 100%|█████████████████████| 19/19 [01:07<00:00,  3.27s/it]Optimising conformer: 100%|█████████████████████| 19/19 [01:07<00:00,  3.55s/it]
Optimising conformer:  40%|█████████▏             | 2/5 [00:40<01:09, 23.08s/it]Optimising conformer:  60%|█████████████▊         | 3/5 [00:45<00:29, 14.63s/it]Optimising conformer:  80%|██████████████████▍    | 4/5 [00:47<00:09,  9.75s/it]Optimising conformer: 100%|███████████████████████| 5/5 [01:16<00:00, 16.70s/it]Optimising conformer: 100%|███████████████████████| 5/5 [01:16<00:00, 15.30s/it]
2024-01-19 08:03:39,335 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:40469
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:40469 after 30 s
2024-01-19 08:03:39,345 - distributed.worker - ERROR - Worker stream died during communication: tcp://10.3.89.124:44379
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 328, in connect
    handshake = await asyncio.wait_for(comm.read(), time_left())
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2081, in gather_dep
    response = await get_data_from_worker(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 2900, in get_data_from_worker
    comm = await rpc.connect(worker)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 333, in connect
    raise OSError(
OSError: Timed out during handshake while connecting to tcp://10.3.89.124:44379 after 30 s
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
TIME Completed the molecule generation in 94.5s.
TIME Completed the molecule generation in 142.2s.
TIME changed dir: 0.0s
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 4 conformers. 
Generated 41 conformers. 
Removed 29 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/4 [00:00<?, ?it/s]Optimising conformer:  25%|█████▊                 | 1/4 [00:03<00:10,  3.42s/it]Optimising conformer:  50%|███████████▌           | 2/4 [00:05<00:05,  2.63s/it]Optimising conformer:  75%|█████████████████▎     | 3/4 [00:07<00:02,  2.31s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.25s/it]Optimising conformer: 100%|███████████████████████| 4/4 [00:09<00:00,  2.39s/it]
TIME Completed the molecule generation in 116.9s.
TIME Completed the molecule generation in 194.4s.
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 6 conformers. 
TIME changed dir: 0.0s
Generated 8 conformers. 
Removed 6 conformers. 
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer:  50%|███████████▌           | 1/2 [00:03<00:03,  3.66s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:05<00:00,  2.80s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:05<00:00,  2.93s/it]
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
TIME Completed the molecule generation in 81.1s.
Optimising conformer:   0%|                               | 0/2 [00:00<?, ?it/s]Optimising conformer:  50%|███████████▌           | 1/2 [00:03<00:03,  3.40s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:05<00:00,  2.52s/it]Optimising conformer: 100%|███████████████████████| 2/2 [00:05<00:00,  2.65s/it]
TIME Completed the molecule generation in 55.1s.
using ani2x
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/resources/
failed to equip `nnpops` with error: No module named 'NNPOps'
Optimising conformer:   0%|                              | 0/12 [00:00<?, ?it/s]Optimising conformer:   8%|█▊                    | 1/12 [00:05<00:55,  5.02s/it]Optimising conformer:  17%|███▋                  | 2/12 [00:07<00:32,  3.27s/it]Optimising conformer:  25%|█████▌                | 3/12 [00:10<00:28,  3.15s/it]Optimising conformer:  33%|███████▎              | 4/12 [00:12<00:21,  2.69s/it]Optimising conformer:  42%|█████████▏            | 5/12 [00:13<00:16,  2.42s/it]Optimising conformer:  50%|███████████           | 6/12 [00:17<00:16,  2.75s/it]Optimising conformer:  58%|████████████▊         | 7/12 [00:19<00:12,  2.43s/it]Optimising conformer:  67%|██████████████▋       | 8/12 [00:21<00:08,  2.24s/it]Optimising conformer:  75%|████████████████▌     | 9/12 [00:23<00:07,  2.45s/it]Optimising conformer:  83%|█████████████████▌   | 10/12 [00:25<00:04,  2.30s/it]Optimising conformer:  92%|███████████████████▎ | 11/12 [00:27<00:02,  2.11s/it]Optimising conformer: 100%|█████████████████████| 12/12 [00:29<00:00,  2.00s/it]Optimising conformer: 100%|█████████████████████| 12/12 [00:29<00:00,  2.44s/it]
2024-01-19 09:24:30,745 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.112:56502 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:30,809 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.112:56504 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:36,185 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:36,186 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.112:41457. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,185 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:36,187 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.112:46077. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,190 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.112:43947'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,191 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.112:36190'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,201 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:36,209 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:36,201 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:36,225 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:38,222 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 71.6s.
2024-01-19 09:24:38,228 - distributed.nanny - ERROR - Worker process died unexpectedly
TIME Completed the molecule generation in 145.6s.
2024-01-19 09:24:41,719 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.112:43947'. Reason: nanny-close-gracefully
2024-01-19 09:24:41,850 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.112:36190'. Reason: nanny-close-gracefully
2024-01-19 09:24:41,851 - distributed.dask_worker - INFO - End worker
