hostname sb011.cluster
ipconfig 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 inet 127.0.0.1/8 scope host lo valid_lft forever preferred_lft forever inet6 ::1/128 scope host valid_lft forever preferred_lft forever 2: enp4s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc mq state UP group default qlen 1000 link/ether a0:8c:f8:61:07:a6 brd ff:ff:ff:ff:ff:ff inet 10.3.81.91/22 brd 10.3.83.255 scope global enp4s0f0 valid_lft forever preferred_lft forever inet6 fe80::a28c:f8ff:fe61:7a6/64 scope link valid_lft forever preferred_lft forever 3: enp4s0f1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:a7 brd ff:ff:ff:ff:ff:ff 4: enp4s0f2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:a8 brd ff:ff:ff:ff:ff:ff 5: enp4s0f3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000 link/ether a0:8c:f8:61:07:a9 brd ff:ff:ff:ff:ff:ff 6: ib0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 4092 qdisc pfifo_fast state UP group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:88:66:39:03:00:23:bb:81 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff inet 10.3.89.91/22 brd 10.3.91.255 scope global ib0 valid_lft forever preferred_lft forever inet 10.3.93.91/22 brd 10.3.95.255 scope global ib0:1 valid_lft forever preferred_lft forever inet6 fe80::8a66:3903:23:bb81/64 scope link valid_lft forever preferred_lft forever 7: ib1: <BROADCAST,MULTICAST> mtu 4092 qdisc noop state DOWN group default qlen 256 link/infiniband 80:00:00:29:fe:80:00:00:00:00:00:00:88:66:39:03:00:23:bb:82 brd 00:ff:ff:ff:ff:12:40:1b:ff:ff:00:00:00:00:00:00:ff:ff:ff:ff
2024-01-19 06:03:32,430 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.91:46007'
2024-01-19 06:03:32,472 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.3.89.91:43598'
2024-01-19 06:03:34,276 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-9v58qvhp', purging
2024-01-19 06:03:34,277 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-jfx380za', purging
2024-01-19 06:03:34,277 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-w_xcwbf4', purging
2024-01-19 06:03:34,278 - distributed.diskutils - INFO - Found stale lock file and directory '/scratch/dask-worker-space/worker-rss9p067', purging
2024-01-19 06:03:44,494 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.91:35953
2024-01-19 06:03:44,495 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.91:35953
2024-01-19 06:03:44,495 - distributed.worker - INFO -           Worker name:         SLURMCluster-390-1
2024-01-19 06:03:44,495 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.91:39936
2024-01-19 06:03:44,495 - distributed.worker - INFO -          dashboard at:           10.3.89.91:39905
2024-01-19 06:03:44,495 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.91:39936
2024-01-19 06:03:44,495 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,495 - distributed.worker - INFO -           Worker name:         SLURMCluster-390-0
2024-01-19 06:03:44,495 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,495 - distributed.worker - INFO -          dashboard at:           10.3.89.91:46290
2024-01-19 06:03:44,495 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,495 - distributed.worker - INFO -               Threads:                          2
2024-01-19 06:03:44,495 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,495 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 06:03:44,495 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-m0m73yle
2024-01-19 06:03:44,495 - distributed.worker - INFO -               Threads:                          2
2024-01-19 06:03:44,495 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,495 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 06:03:44,495 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-5qcufadl
2024-01-19 06:03:44,496 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,570 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,570 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,571 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 06:03:44,573 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 06:03:44,573 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:03:44,574 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 06:06:36,806 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.15s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 06:06:36,806 - distributed.core - INFO - Event loop was unresponsive in Worker for 6.16s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 06:15:51,974 - distributed.core - INFO - Event loop was unresponsive in Worker for 24.92s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/parmed/structure.py:1775: UnitStrippedWarning: The unit of the quantity is stripped when downcasting to ndarray.
  coords = np.array(value, dtype=np.float64, copy=False, subok=True)
/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/torchani/__init__.py:55: UserWarning: Dependency not satisfied, torchani.ase will not be available
  warnings.warn("Dependency not satisfied, torchani.ase will not be available")
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
2024-01-19 06:16:59,125 - distributed.nanny - INFO - Worker process 6308 was killed by signal 11
2024-01-19 06:16:59,132 - distributed.nanny - WARNING - Restarting worker
2024-01-19 06:17:06,059 - distributed.worker - INFO -       Start worker at:     tcp://10.3.89.91:39806
2024-01-19 06:17:06,060 - distributed.worker - INFO -          Listening to:     tcp://10.3.89.91:39806
2024-01-19 06:17:06,060 - distributed.worker - INFO -           Worker name:         SLURMCluster-390-0
2024-01-19 06:17:06,060 - distributed.worker - INFO -          dashboard at:           10.3.89.91:43752
2024-01-19 06:17:06,060 - distributed.worker - INFO - Waiting to connect to:     tcp://10.3.88.12:42763
2024-01-19 06:17:06,060 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:17:06,060 - distributed.worker - INFO -               Threads:                          2
2024-01-19 06:17:06,060 - distributed.worker - INFO -                Memory:                  10.24 GiB
2024-01-19 06:17:06,060 - distributed.worker - INFO -       Local Directory: /scratch/dask-worker-space/worker-3j4fzwwq
2024-01-19 06:17:06,060 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:17:06,100 - distributed.worker - INFO -         Registered to:     tcp://10.3.88.12:42763
2024-01-19 06:17:06,100 - distributed.worker - INFO - -------------------------------------------------
2024-01-19 06:17:06,101 - distributed.core - INFO - Starting established connection to tcp://10.3.88.12:42763
2024-01-19 07:54:32,058 - distributed.core - INFO - Event loop was unresponsive in Worker for 10.04s.  This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
2024-01-19 09:24:30,512 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.91:57046 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:30,704 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://10.3.89.91:57080 remote=tcp://10.3.88.12:42763>: TimeoutError: [Errno 110] Connection timed out
2024-01-19 09:24:36,144 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:36,145 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.91:35953. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,149 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.91:43598'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:36,159 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:36,179 - distributed.nanny - INFO - Worker closed
2024-01-19 09:24:38,189 - distributed.nanny - ERROR - Worker process died unexpectedly
2024-01-19 09:24:38,946 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.91:43598'. Reason: nanny-close-gracefully
2024-01-19 09:24:57,649 - distributed.core - INFO - Connection to tcp://10.3.88.12:42763 has been closed.
2024-01-19 09:24:57,651 - distributed.worker - INFO - Stopping worker at tcp://10.3.89.91:39806. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,661 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.3.89.91:46007'. Reason: worker-handle-scheduler-connection-broken
2024-01-19 09:24:57,667 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1389, in _connect
    comm = await connect(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/comm/core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/asyncio/tasks.py", line 466, in wait_for
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1224, in send_recv_from_rpc
    comm = await self.pool.connect(self.addr)
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1468, in connect
    return await connect_attempt
  File "/mnt/storage/nobackup/nmb1063/mamba/envs/fegrow/lib/python3.9/site-packages/distributed/core.py", line 1412, in _connect
    raise CommClosedError(reason)
distributed.comm.core.CommClosedError: ConnectionPool closing.
2024-01-19 09:24:57,675 - distributed.nanny - INFO - Worker closed
2024-01-19 09:25:00,215 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.3.89.91:46007'. Reason: nanny-close-gracefully
2024-01-19 09:25:00,216 - distributed.dask_worker - INFO - End worker
